//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APARATO
    {
        public int codigo_Aparato { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Descripcion { get; set; }
        public int codigo_Estado { get; set; }
        public int codigo_Sala { get; set; }
        public int codigo_Empleado { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual SALA SALA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
