//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASE()
        {
            this.DETALLE_MATRICULA = new HashSet<DETALLE_MATRICULA>();
        }
    
        public int codigo_Clase { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Descripcion { get; set; }
        public int codigo_Dia { get; set; }
        public int codigo_hora { get; set; }
        public int codigo_Monitor { get; set; }
        public int codigo_Sala { get; set; }
        public int codigo_Empleado { get; set; }
    
        public virtual DIA DIA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HORA HORA { get; set; }
        public virtual MONITOR MONITOR { get; set; }
        public virtual SALA SALA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_MATRICULA> DETALLE_MATRICULA { get; set; }
    }
}
