//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_MATRICULA
    {
        public int codigo_DetallesMatr { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public int codigo_Clase { get; set; }
        public int codigo_Matricula { get; set; }
    
        public virtual CLASE CLASE { get; set; }
        public virtual MATRICULA MATRICULA { get; set; }
    }
}
