//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECI_MONI
    {
        public int codigo_Especi_Moni { get; set; }
        public int codigo_Especialidad { get; set; }
        public int codigo_Monitor { get; set; }
    
        public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
        public virtual MONITOR MONITOR { get; set; }
    }
}
