//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIMNASIOEntities : DbContext
    {
        public GIMNASIOEntities()
            : base("name=GIMNASIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APARATO> APARATOes { get; set; }
        public virtual DbSet<CIUDAD> CIUDADs { get; set; }
        public virtual DbSet<CLASE> CLASEs { get; set; }
        public virtual DbSet<DETALLE_MATRICULA> DETALLE_MATRICULA { get; set; }
        public virtual DbSet<DIA> DIAs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<ESPECI_MONI> ESPECI_MONI { get; set; }
        public virtual DbSet<ESPECIALIDAD> ESPECIALIDADs { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<HORA> HORAS { get; set; }
        public virtual DbSet<MATRICULA> MATRICULAs { get; set; }
        public virtual DbSet<MONITOR> MONITORs { get; set; }
        public virtual DbSet<PROFESION> PROFESIONs { get; set; }
        public virtual DbSet<SALA> SALAs { get; set; }
        public virtual DbSet<SOCIO> SOCIOs { get; set; }
        public virtual DbSet<TELEFONO> TELEFONOes { get; set; }
        public virtual DbSet<TIPO_DOC> TIPO_DOC { get; set; }
        public virtual DbSet<TIPO_SALA> TIPO_SALA { get; set; }
        public virtual DbSet<TIPO_TEL> TIPO_TEL { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
