//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALA()
        {
            this.APARATOes = new HashSet<APARATO>();
            this.CLASEs = new HashSet<CLASE>();
        }
    
        public int codigo_Sala { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int Metros_Cuadrados { get; set; }
        public string Ubicacion { get; set; }
        public int codigo_Tipo { get; set; }
        public int codigo_Empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APARATO> APARATOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASE> CLASEs { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual TIPO_SALA TIPO_SALA { get; set; }
    }
}
