//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public int codigo_Telefono { get; set; }
        public double Numero { get; set; }
        public int codigo_Tipo { get; set; }
        public int codigo_Socio { get; set; }
    
        public virtual SOCIO SOCIO { get; set; }
        public virtual TIPO_TEL TIPO_TEL { get; set; }
    }
}
