//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiGimnasio.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int Clave { get; set; }
        public string Contrasenia { get; set; }
        public int codigo_EMPLEADO { get; set; }
        public Nullable<bool> Activo { get; set; }

        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
